version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: airport-manager
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airport-manager
    ports:
      - '5432:5432'
